### ISSUE TITLE
Issue related Akamai Decryption and Merging

### ISSUE THREAD

**Issue by chintapakdumdum22** [DevLARLEY/player.akamai.net.in#1]
Dear Larley,

I hope you like this post. I used your N_m3u8DL-RE repo and I am having an issue with .tsa/.tsb/.tsc/.tsd/.tse fragment decoding. The fragment is not getting decoded properly which is giving an error while merging the decrypted fragment.

Can you improve the code? I will send you the m3u8 link with key and IV, you can test it and see what error is coming. I don't think it will be safe to attach the link here, you tell me where I can contact you, I will send you the m3u8 link.

Thank you for considering my issue I look forward to hearing from you.

Best regards,
Aryan Raj

**Comment by DevLARLEY** [comment]
Some questions first:
+ Did you make sure to download the correct build of N_m3u8DL-RE (the ZIPs below 1MB starting with `N_m3u8DL-RE_Beta_build...`)?
+ Which of the extensions are you dealing with? I wasn't able to test all of them.

**Comment by chintapakdumdum22** [comment]
Yes, I downloaded the correct build of N_m3u8DL-RE (N_m3u8DL-RE_Beta_build-win-x64_20241014.zip). And I am dealing with all extensions .tsa/.tsb/.tsc/.tsd/.tse.

Please check this 
https://appx-transcoded-videos-mcdn.akamai.net.in/videos/yesofficer-data/137230-1729156619/hls-drm-82a1bc/360p/master-720267.1809834449.m3u8
KEY: 53a505853865cee5a9a0824f27e2c95f
IV: 8487c82f16ba7271e2238bf58fe7f09f

**Comment by DevLARLEY** [comment]
You should use the HLS file generated by the python script as input to N_m3u8DL-RE.

**Comment by chintapakdumdum22** [comment]
The generated json file also contains the hls-drm link with the base64 key and IV

**Comment by DevLARLEY** [comment]
Where did you get that manifest url from? The manifest should be encrypted in the secure-player response

**Comment by chintapakdumdum22** [comment]
There is an edtech platform called [yesofficer](https://www.yesofficer.com/). I got this link from there.

Actually, I got the fragment link from the network section of developer tools. The fragment in the [photo](https://github.com/DevLARLEY/player.akamai.net.in/issues/1#issuecomment-2419780546) I have attached in the previous comment above is the same fragment link. And then I changed its extension with m3u8..

**Comment by DevLARLEY** [comment]
So:
+ You got a fragment link from yesofficer
+ Replaced its the extension with `.m3u8` 
But where did you get the key from?

**Comment by chintapakdumdum22** [comment]
I have taken API (which is a link) from someone which gets the key and gives it to me. For this I have written a simple code which extracts URI from m3u8 link and appends it to API link and then gets the key from that API.

**Comment by DevLARLEY** [comment]
Does my script not _work_?

**Comment by chintapakdumdum22** [comment]
Your script is working but only 1 out of 3 links is decrypting and merging correctly. Try downloading, decrypting and merging the link I sent in the previous comment ([this one](https://github.com/DevLARLEY/player.akamai.net.in/issues/1#issuecomment-2419636504)).

**Comment by DevLARLEY** [comment]
Works fine

**Comment by chintapakdumdum22** [comment]
How ?

What command did you use?

**Comment by DevLARLEY** [comment]
`N_m3u8DL-RE "yesofficer.m3u8" --base-url "https://appx-transcoded-videos-mcdn.akamai.net.in/videos/yesofficer-data/137230-1729156619/hls-drm-82a1bc/360p/" --del-after-done False --thread-count 1`
yesofficer.m3u8:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="yesofficer.key",IV=0x8487c82f16ba7271e2238bf58fe7f09f
#EXTINF:10.416667,
master-720267.1809834449-0.tsc
#EXTINF:10.416667,
master-720267.1809834449-1.tsc
...
```
yesofficer.key containing your key in bytes

**Comment by chintapakdumdum22** [comment]
![error](https://github.com/user-attachments/assets/924d8edd-c78a-4858-bdba-fe3cf9d33258)
It show error...

**Comment by DevLARLEY** [comment]
did you place ffmpeg in the folder?

**Comment by chintapakdumdum22** [comment]
Yes, I placed ffmpeg in the same folder as N_m3u8DL-RE

**Comment by DevLARLEY** [comment]
Then I don't know. Download the newest version of ffmpeg?

**Comment by chintapakdumdum22** [comment]
Yes, i am using newest version of ffmpeg which is 7.0.1.

N_m3u8DL-RE "yesofficer.m3u8" --base-url "https://appx-transcoded-videos-mcdn.akamai.net.in/videos/yesofficer-data/137230-1729156619/hls-drm-82a1bc/240p/" --custom-hls-key 53a505853865cee5a9a0824f27e2c95f --custom-hls-iv 8487c82f16ba7271e2238bf58fe7f09f --del-after-done False --thread-count 1

I used this command and it is showing me this error

![Capture](https://github.com/user-attachments/assets/b983101e-38b6-42c7-9bf7-c46ac1fb514f)

**Comment by DevLARLEY** [comment]
Is the video playable? It was throwing these errors for me too

**Comment by chintapakdumdum22** [comment]
`Invalid data found while processing input` This error came because the key in 'yesofficer.key' was in bytes and IV was in hex.
But when I gave this command

`N_m3u8DL-RE "yesofficer.m3u8" --base-url "https://appx-transcoded-videos-mcdn.akamai.net.in/videos/yesofficer-data/137230-1729156619/hls-drm-82a1bc/240p/" --custom-hls-key 53a505853865cee5a9a0824f27e2c95f --custom-hls-iv 8487c82f16ba7271e2238bf58fe7f09f --del-after-done False --thread-count 1`

the fragments got downloaded but not decoded properly. The downloaded fragments are playable but frames are getting stuck.

**Comment by DevLARLEY** [comment]
I had hicks too in the fragments, but the final video played fine.

**Comment by chintapakdumdum22** [comment]
How did you do it?

**Comment by DevLARLEY** [comment]
Run the command I posted earlier and player the video after waiting for it to finish
