### ISSUE TITLE
 Corrupt video output when using N_m3u8DL-RE on test.m3u8 generated by akamai_player.py

### ISSUE THREAD

**Issue by imsexydroid** [DevLARLEY/player.akamai.net.in#2]
I'm experiencing an issue where the video output is corrupt when using N_m3u8DL-RE on a test.m3u8 file generated by akamai_player.py. The process ends with a warning about invalid data, and the resulting video cannot be played.

**Steps to Reproduce**

1. Run akamai_player.py to generate test.m3u8.
2. Execute the following command:
`N_m3u8DL-RE_Beta_build-linux-x64/N_m3u8DL-RE test.m3u8 --thread-count 1`
3. Observe the console output and check the generated video file.

**Expected Behavior**

- The video should download and output correctly without any corruption.
- No warnings or errors should appear during the process.

Actual Behavior

- The process ends with the following warning:
`07:10:06.828 WARN : concat:0.ts|1.ts|2.ts|: Invalid data found when processing input`
- The resulting video file is corrupt and unplayable.

**Console Output**
```
07:09:52.984 INFO : N_m3u8DL-RE (Beta version) 20240630
07:09:53.266 INFO : Loading URL: test.m3u8
07:09:53.283 INFO : Content Matched: HTTP Live Streaming
07:09:53.295 INFO : Parsing streams...
07:09:53.300 WARN : Master List detected, try parse all streams
07:09:53.619 WARN : Writing meta json
07:09:53.630 INFO : Extracted, there are 5 streams, with 5 basic streams, 0 audio streams, 0 subtitle streams
07:09:53.637 INFO : Vid 1080x1920 | 0 Kbps
07:09:53.638 INFO : Vid 720x1280 | 0 Kbps
07:09:53.638 INFO : Vid 480x853 | 0 Kbps
07:09:53.639 INFO : Vid 360x640 | 0 Kbps
07:09:53.641 INFO : Vid 240x427 | 0 Kbps
Please select what you want to download:             

> [ ] Basic                                          
    [X] Vid 1080x1920 | 0 Kbps                       
    [ ] Vid 720x1280 | 0 Kbps                        
    [ ] Vid 480x853 | 0 Kbps                         
    [ ] Vid 360x640 | 0 Kbps                         
    [ ] Vid 240x427 | 0 Kbps                         

Please select what you want to download:             

> [ ] Basic                                          
    [X] Vid 1080x1920 | 0 Kbps                       
    [ ] Vid 720x1280 | 0 Kbps                        
    [ ] Vid 480x853 | 0 Kbps                         
    [ ] Vid 360x640 | 0 Kbps                         
    [ ] Vid 240x427 | 0 Kbps           
07:09:58.053 INFO : Parsing streams...
07:09:58.103 INFO : Selected streams:
07:09:58.111 INFO : Vid *AKAMAI_TSE 1080x1920 | 0 Kbps | 3 Segments | ~00m10s
07:09:58.112 WARN : Writing meta json
07:09:58.114 INFO : Save Name: test_2024-10-24_07-09-53
07:09:58.161 INFO : Start downloading...Vid 1080x1920 | 0 Kbps

07:10:06.828 WARN : concat:0.ts|1.ts|2.ts|: Invalid data found when processing input
```

Similar error if I try to pass a specific quality m3u8 with --custom-hls-key and it's respective key file.
Could you please investigate this issue? Let me know if you need any more information or if there are any troubleshooting steps I can try.

**Comment by DevLARLEY** [comment]
Could you provide me with the test.m3u8 file to be able to reproduce the issue?

**Comment by imsexydroid** [comment]
where do i send it to you?
